// <auto-generated />
using System;
using FoxMapperBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoxMapperBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251116174636_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("FoxMapperBackend.Models.Courier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("LastUpdatedUtc");

                    b.ToTable("Couriers");
                });

            modelBuilder.Entity("FoxMapperBackend.Models.DeliveryRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourierId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepotId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CourierId");

                    b.HasIndex("DepotId");

                    b.HasIndex("LastUpdatedUtc");

                    b.HasIndex("Status");

                    b.ToTable("DeliveryRuns");
                });

            modelBuilder.Entity("FoxMapperBackend.Models.Depot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressLine")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("Lat")
                        .HasColumnType("REAL");

                    b.Property<double>("Lng")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastUpdatedUtc");

                    b.ToTable("Depots");
                });

            modelBuilder.Entity("FoxMapperBackend.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressLine")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("Lat")
                        .HasColumnType("REAL");

                    b.Property<double>("Lng")
                        .HasColumnType("REAL");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryRunId");

                    b.HasIndex("ExternalCode");

                    b.HasIndex("LastUpdatedUtc");

                    b.HasIndex("Status");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("FoxMapperBackend.Models.RouteStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryRunId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("Lat")
                        .HasColumnType("REAL");

                    b.Property<double>("Lng")
                        .HasColumnType("REAL");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PlannedArrivalUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LastUpdatedUtc");

                    b.HasIndex("PackageId");

                    b.HasIndex("DeliveryRunId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("RouteStops");
                });

            modelBuilder.Entity("FoxMapperBackend.Models.DeliveryRun", b =>
                {
                    b.HasOne("FoxMapperBackend.Models.Courier", "Courier")
                        .WithMany("DeliveryRuns")
                        .HasForeignKey("CourierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoxMapperBackend.Models.Depot", "Depot")
                        .WithMany("DeliveryRuns")
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Courier");

                    b.Navigation("Depot");
                });

            modelBuilder.Entity("FoxMapperBackend.Models.Package", b =>
                {
                    b.HasOne("FoxMapperBackend.Models.DeliveryRun", "DeliveryRun")
                        .WithMany("Packages")
                        .HasForeignKey("DeliveryRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryRun");
                });

            modelBuilder.Entity("FoxMapperBackend.Models.RouteStop", b =>
                {
                    b.HasOne("FoxMapperBackend.Models.DeliveryRun", "DeliveryRun")
                        .WithMany("RouteStops")
                        .HasForeignKey("DeliveryRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoxMapperBackend.Models.Package", "Package")
                        .WithMany("RouteStops")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DeliveryRun");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("FoxMapperBackend.Models.Courier", b =>
                {
                    b.Navigation("DeliveryRuns");
                });

            modelBuilder.Entity("FoxMapperBackend.Models.DeliveryRun", b =>
                {
                    b.Navigation("Packages");

                    b.Navigation("RouteStops");
                });

            modelBuilder.Entity("FoxMapperBackend.Models.Depot", b =>
                {
                    b.Navigation("DeliveryRuns");
                });

            modelBuilder.Entity("FoxMapperBackend.Models.Package", b =>
                {
                    b.Navigation("RouteStops");
                });
#pragma warning restore 612, 618
        }
    }
}
